# This file contains sensitive information and should not be shared publicly.
# Ensure this file is kept secure and not included in version control.

mlflow:
  password: fc6e085ac3b8*****************************
 
aws:
  access_key_path: '/thien/thien_devops_accessKeys.csv'

email:
  password: 'abc def ghi kkkk'

github:
  token: 'ghp_abcdefghijklmnopqrstuvwxyz1234567890'