name: Echo and Notify

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        id: echo-step
        run: |
          echo "Echo job succeeded!"
  echo-job2:
    runs-on: ubuntu-latest
    needs: [echo-job]
    steps:
      - name: Echo something
        id: echo-step
        run: |
          echo "Echo job succeeded!"

  echo-job3:
    runs-on: ubuntu-latest
    needs: [echo-job]
    steps:
      - name: Echo something
        id: echo-step
        run: |
          echo "Echo job succeeded!"
  echo-job4:
    runs-on: ubuntu-latest
    needs: [echo-job2, echo-job3]
    steps:
      - name: Echo something
        id: echo-step
        run: |
          echo "Echo job succeeded!"
          cd cd
          
  notify_success:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: [echo-job4]
    steps:
    - name: Send success email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "MLOps Pipeline Success"
        body: "The MLOps pipeline has completed successfully."
        to: ${{ secrets.NOTIFY_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        status: ${{ needs.echo-job.outputs.status }}  # Using the output from echo-job

  notify_failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [echo-job4]
    steps:
    - name: Send failure email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "MLOps Pipeline Failure"
        body: "The MLOps pipeline has failed. Please check the logs for details."
        to: ${{ secrets.NOTIFY_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        status: ${{ needs.echo-job.outputs.status }}  # Using the output from echo-job
