name: Provisioning Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  provision_infrastructure:
    runs-on: ubuntu-latest
    steps:
          
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          ls
          cd infra/vpc-ec2-sg-remote-backend-kltn
          ls
          echo "${{ secrets.EMR_KEY }}" > emr.pem
          chmod 600 emr.pem
          ls
     
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version
          
        

