name: Provisioning Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  provision_infrastructure:
    runs-on: ubuntu-latest
    steps:
          
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          ls
          cd /kltn-sentiment-monitoring-mlops/infra/vpc-ec2-remote-backend-kltn
          ls
          echo "${{ secrets.EMR_KEY }}" > emr.pem
          chmod 600 emr.pem
          ls
        

